name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integration:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">1.17.2"

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: |
          make fmt
          make install
          make test-ci
